# -*- coding: utf-8 -*-
"""DecisionTreeImplementation

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v0cJJKXWE1_9Nj9SUV5PriD8B5sV0ASU
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

iris=pd.read_csv('iris.csv')
iris.head()
#iris.shape

x=pd.DataFrame(iris[['sepal_length','sepal_width','petal_length','petal_width']])
y=pd.DataFrame(iris['species'])

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.20)

from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier()
classifier.fit(x_train,y_train) #training datasets

y_pred=classifier.predict(x_test) #predicting y on x test datasets

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))
#now check the usability using cm left diagonal of the metrics shows the correct prediction others are wrong prediction

#Now calculating accuracy score
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))