# -*- coding: utf-8 -*-
"""SupportVectorMachine(SVM)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17S5J1cDbSBaBqu0QK6ErINn23SG2GxYZ
"""

from sklearn import datasets
cancer=datasets.load_breast_cancer()
cancer.feature_names
cancer.target_names

print(cancer.data[0:5]) # printing first five records

print(cancer.target) #printing target values where 0 is patient tumer is meliant and 1 for benign

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(cancer.data,cancer.target,train_size=0.3,random_state=109)

from sklearn import svm
clf=svm.SVC(kernel='linear')
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)

from sklearn import metrics
metrics.confusion_matrix(y_test,y_pred)

metrics.accuracy_score(y_test,y_pred)